/**
 * Regenerates src/data/globeLand.ts - the land mask the Speaking globe is
 * drawn from. Run with `npm run generate:globe` (needs network access).
 *
 * Natural Earth land polygons (public domain) are sampled on a sphere: one row
 * per latitude, with the number of longitude samples scaled by cos(lat) so the
 * dots stay evenly spaced instead of bunching up towards the poles. Each row is
 * packed into a bit mask and base64-encoded, which keeps ~17k samples in a few
 * kilobytes - the browser decodes them back into unit vectors at load.
 */
import { writeFileSync } from 'node:fs';

const SOURCE =
  'https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json';

/** Antarctica is dropped - it would be a big empty cap with no events on it. */
const LAT_START = -58;
const LAT_END = 84;
/** Degrees between rows; also sets the spacing along the equator. */
const LAT_STEP = 1.5;
/** Longitude samples at the equator; every row scales this by cos(lat). */
const EQUATOR_SAMPLES = 240;

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`Failed to fetch land polygons: ${response.status}`);
const geo = await response.json();

/** Flatten to a list of polygons, each an array of rings (outer ring first). */
const polygons = [];
for (const feature of geo.features) {
  const { type, coordinates } = feature.geometry;
  const parts = type === 'Polygon' ? [coordinates] : coordinates;
  for (const rings of parts) polygons.push(rings);
}

/** Bounding box per polygon - cheap rejection before the ray cast. */
const boxes = polygons.map(([outer]) => {
  let minLng = Infinity;
  let minLat = Infinity;
  let maxLng = -Infinity;
  let maxLat = -Infinity;
  for (const [lng, lat] of outer) {
    if (lng < minLng) minLng = lng;
    if (lng > maxLng) maxLng = lng;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  return [minLng, minLat, maxLng, maxLat];
});

const inRing = (ring, lng, lat) => {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};

const isLand = (lng, lat) => {
  for (let p = 0; p < polygons.length; p += 1) {
    const [minLng, minLat, maxLng, maxLat] = boxes[p];
    if (lng < minLng || lng > maxLng || lat < minLat || lat > maxLat) continue;
    const rings = polygons[p];
    if (!inRing(rings[0], lng, lat)) continue;
    // Skip lakes and other holes punched into the outer ring.
    if (rings.slice(1).some((ring) => inRing(ring, lng, lat))) continue;
    return true;
  }
  return false;
};

const rows = [];
let samples = 0;
let dots = 0;

for (let lat = LAT_START; lat <= LAT_END + 1e-9; lat += LAT_STEP) {
  const count = Math.max(1, Math.round(EQUATOR_SAMPLES * Math.cos((lat * Math.PI) / 180)));
  let bits = '';
  let chunk = 0;

  for (let i = 0; i < count; i += 1) {
    const lng = -180 + ((i + 0.5) * 360) / count;
    if (isLand(lng, lat)) {
      chunk |= 1 << (5 - (i % 6));
      dots += 1;
    }
    if (i % 6 === 5) {
      bits += B64[chunk];
      chunk = 0;
    }
  }

  if (count % 6 !== 0) bits += B64[chunk];
  samples += count;
  rows.push(`${count}:${bits}`);
}

const file = `// Generated by scripts/generate-globe.mjs - do not edit by hand.
// Source: Natural Earth 1:110m land polygons (public domain).

/** Latitude of the first row, in degrees. */
export const latStart = ${LAT_START};
/** Degrees between rows. */
export const latStep = ${LAT_STEP};

/**
 * One row per latitude as \`<sample count>:<base64 bit mask>\`, rows separated by
 * commas. A set bit means the sample at that longitude is land. ${dots} of
 * ${samples} samples are land.
 */
export const landRows =
  '${rows.join(',')}';
`;

writeFileSync(new URL('../src/data/globeLand.ts', import.meta.url), file);
console.log(`Wrote src/data/globeLand.ts - ${rows.length} rows, ${dots}/${samples} land samples.`);
